version: '2'
volumes:
  yarn-cache:
  node-modules:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    ports:
      - 8080:80
  test_client:
    build:
      context: .
      dockerfile: /docker/Dockerfile-test_client
    depends_on:
      - app
    environment:
      - TARGET_HOST=http://app
    volumes:
      - node-modules:/src/node_modules/
      - yarn-cache:/root/.cache/
    external_links:
      # These are all the `server_name`s that the nginx server is listening on
      - app:pif.gov
      - app:www.pif.gov
      - app:connect.gov
      - app:www.connect.gov
      - app:18f.gov
      - app:www.18f.gov
      - app:app.gov
      - app:www.app.gov
      - app:jobs.18f.gov
      - app:join.18f.gov
      - app:pages.18f.gov
      - app:digitalgov.gov
      - app:www.digitalgov.gov
